version: '3'

networks:
  internal:
    driver: bridge

services:
  env:
    build: .
    image: devix
    container_name: devix-env
    volumes:
      - ~/Projects:/home/develop/Projects
      - ~/.ssh:/home/develop/.ssh
      - ~/.oh-my-zsh:/home/develop/.oh-my-zsh
      - ~/.oh-my-git:/home/develop/.oh-my-git
      - ~/.antigen:/home/develop/.antigen
      - ./data/redis:/var/lib/redis
    ports:
      - "3001:3000"
      - "9201:9200"
    shm_size: 2GB
    tty: true
    stdin_open: true
    environment:
      - NODE_ENV=development
      - RAILS_ENV=development
      - DEVELOPMENT_ENV=docker
    depends_on:
      - db_pg
      - db_mysql
    networks:
      - internal

  db_pg:
    image: devix-postgres
    container_name: devix-postgres
    ports:
     - "9000:5432"
    shm_size: 500MB
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    tty: true
    stdin_open: true
    networks:
      - internal

  db_mysql:
    image: devix-mysql
    container_name: devix-mysql
    ports:
     - "8083:3306"
    shm_size: 500MB
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - internal
