version: '3'

networks:
  internal:
    driver: bridge

services:
  web:
    build: .
    image: tween-pb
    container_name: tween-pb-web
    volumes:
      - ~/Projects/precios_bajos:/home/deploy/Projects/precios_bajos
      - ~/.ssh:/home/deploy/.ssh
      - ./data/redis:/var/lib/redis
    ports:
      - "3001:3000"
      - "9201:9200"
    shm_size: 2GB
    tty: true
    stdin_open: true
    environment:
      - RAILS_ENV=development
      - DEVELOPMENT_ENV=docker
    depends_on:
      - db_pg
      - db_mysql
    networks:
      - internal

  db_pg:
    image: tween-pb-postgres
    container_name: tween-pb-postgres
    ports:
     - "9000:5432"
    shm_size: 500MB
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    tty: true
    stdin_open: true
    networks:
      - internal

  db_mysql:
    image: tween-pb-mysql
    container_name: tween-pb-mysql
    ports:
     - "8083:3306"
    shm_size: 500MB
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - internal
